"#include \"ScreenSpaceReflectionStructures.fxh\"\n"
"#include \"SSR_Common.fxh\"\n"
"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"\n"
"cbuffer cbScreenSpaceReflectionAttribs\n"
"{\n"
"    ScreenSpaceReflectionAttribs g_SSRAttribs;\n"
"}\n"
"\n"
"Texture2D<float4> g_TextureMaterialParameters;\n"
"Texture2D<float>  g_TextureDepth;\n"
"\n"
"float SampleRoughness(int2 PixelCoord)\n"
"{\n"
"    float Roughness = g_TextureMaterialParameters.Load(int3(PixelCoord, 0))[g_SSRAttribs.RoughnessChannel];\n"
"    if (!g_SSRAttribs.IsRoughnessPerceptual)\n"
"        Roughness = sqrt(Roughness);\n"
"    return Roughness;\n"
"}\n"
"\n"
"float SampleDepth(int2 PixelCoord)\n"
"{\n"
"    return g_TextureDepth.Load(int3(PixelCoord, 0));\n"
"}\n"
"\n"
"float ComputeStencilMaskAndExtractRoughnessPS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float Roughness = SampleRoughness(int2(VSOut.f4PixelPos.xy));\n"
"    float Depth = SampleDepth(int2(VSOut.f4PixelPos.xy));\n"
"    if (!IsReflectionSample(Roughness, Depth, g_SSRAttribs.RoughnessThreshold))\n"
"        discard;\n"
"\n"
"    return Roughness;\n"
"}\n"
