"\n"
"void main(in  uint   VertexId : SV_VertexID,\n"
"          out float4 Pos      : SV_Position,\n"
"          out float4 ClipPos  : CLIP_POS)\n"
"{\n"
"    float2 PosXY[3];\n"
"    PosXY[0] = float2(-1.0, -1.0);\n"
"    PosXY[1] = float2(-1.0, +3.0);\n"
"    PosXY[2] = float2(+3.0, -1.0);\n"
"\n"
"    float2 f2XY = PosXY[VertexId];\n"
"    Pos = float4(f2XY, 1.0, 1.0);\n"
"    ClipPos = Pos;\n"
"}\n"
