"#include \"BasicStructures.fxh\"\n"
"#include \"ToneMapping.fxh\"\n"
"\n"
"cbuffer cbCameraAttribs\n"
"{\n"
"    CameraAttribs g_CameraAttribs;\n"
"}\n"
"\n"
"cbuffer cbEnvMapRenderAttribs\n"
"{\n"
"    ToneMappingAttribs g_ToneMappingAttribs;\n"
"\n"
"    float AverageLogLum;\n"
"    float MipLevel;\n"
"    float Unusued1;\n"
"    float Unusued2;\n"
"}\n"
"\n"
"TextureCube  EnvMap;\n"
"SamplerState EnvMap_sampler;\n"
"\n"
"void main(in  float4 Pos     : SV_Position,\n"
"          in  float4 ClipPos : CLIP_POS,\n"
"          out float4 Color   : SV_Target)\n"
"{\n"
"    float4 WorldPos = mul(ClipPos, g_CameraAttribs.mViewProjInv);\n"
"    float3 Direction = WorldPos.xyz / WorldPos.w - g_CameraAttribs.f4Position.xyz;\n"
"    float3 EnvRadiance = EnvMap.SampleLevel(EnvMap_sampler, Direction, MipLevel).rgb;\n"
"    Color.rgb = ToneMap(EnvRadiance.rgb, g_ToneMappingAttribs, AverageLogLum);\n"
"#if CONVERT_OUTPUT_TO_SRGB\n"
"    Color.rgb = pow(Color.rgb, float3(1.0 / 2.2, 1.0 / 2.2, 1.0 / 2.2));\n"
"#endif\n"
"    Color.a = 1.0;\n"
"}\n"
