"\n"
"struct GLTF_VS_Output\n"
"{\n"
"    float4 Pos      : SV_Position;\n"
"    float3 WorldPos : WORLD_POS;\n"
"    float3 Normal   : NORMAL;\n"
"    float2 UV0      : UV0;\n"
"    float2 UV1      : UV1;\n"
"};\n"
