"#ifndef _GLTF_PBR_STRUCTURES_FXH_\n"
"#define _GLTF_PBR_STRUCTURES_FXH_\n"
"\n"
"#ifdef __cplusplus\n"
"\n"
"#   ifndef CHECK_STRUCT_ALIGNMENT\n"
"        // Note that defining empty macros causes GL shader compilation error on Mac, because\n"
"        // it does not allow standalone semicolons outside of main.\n"
"        // On the other hand, adding semicolon at the end of the macro definition causes gcc error.\n"
"#       define CHECK_STRUCT_ALIGNMENT(s) static_assert( sizeof(s) % 16 == 0, \"sizeof(\" #s \") is not multiple of 16\" )\n"
"#   endif\n"
"\n"
"#endif\n"
"\n"
"#ifndef PBR_WORKFLOW_METALLIC_ROUGHNESS\n"
"#   define PBR_WORKFLOW_METALLIC_ROUGHNESS 0\n"
"#endif\n"
"\n"
"#ifndef PBR_WORKFLOW_SPECULAR_GLOSINESS\n"
"#   define PBR_WORKFLOW_SPECULAR_GLOSINESS 1\n"
"#endif\n"
"\n"
"\n"
"#ifndef GLTF_ALPHA_MODE_OPAQUE\n"
"#   define GLTF_ALPHA_MODE_OPAQUE 0\n"
"#endif\n"
"\n"
"#ifndef GLTF_ALPHA_MODE_MASK\n"
"#   define GLTF_ALPHA_MODE_MASK 1\n"
"#endif\n"
"\n"
"#ifndef GLTF_ALPHA_MODE_BLEND\n"
"#   define GLTF_ALPHA_MODE_BLEND 2\n"
"#endif\n"
"\n"
"\n"
"struct GLTFNodeShaderTransforms\n"
"{\n"
"	float4x4 NodeMatrix;\n"
"\n"
"	int      JointCount;\n"
"    float    Dummy0;\n"
"    float    Dummy1;\n"
"    float    Dummy2;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(GLTFNodeShaderTransforms);\n"
"#endif\n"
"\n"
"\n"
"struct GLTFRendererShaderParameters\n"
"{\n"
"	float AverageLogLum;\n"
"	float MiddleGray;\n"
"    float WhitePoint;\n"
"	float PrefilteredCubeMipLevels;\n"
"\n"
"	float IBLScale;\n"
"	int   DebugViewType;\n"
"    float OcclusionStrength;\n"
"    float EmissionScale;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(GLTFRendererShaderParameters);\n"
"#endif\n"
"\n"
"struct GLTFMaterialShaderInfo\n"
"{\n"
"	float4  BaseColorFactor;\n"
"	float4  EmissiveFactor;\n"
"	float4  SpecularFactor;\n"
"\n"
"	int     Workflow;\n"
"	float   BaseColorTextureUVSelector;\n"
"	float   PhysicalDescriptorTextureUVSelector;\n"
"	float   NormalTextureUVSelector; \n"
"\n"
"	float   OcclusionTextureUVSelector;\n"
"	float   EmissiveTextureUVSelector;\n"
"    float   BaseColorSlice;\n"
"    float   PhysicalDescriptorSlice;\n"
"\n"
"    float   NormalSlice;\n"
"    float   OcclusionSlice;\n"
"    float   EmissiveSlice;\n"
"	float   MetallicFactor;\n"
"\n"
"	float   RoughnessFactor;\n"
"	int     AlphaMode;	\n"
"	float   AlphaMaskCutoff;\n"
"    float   Dummy0;\n"
"\n"
"    // When texture atlas is used, UV scale and bias applied to\n"
"    // each texture coordinate set\n"
"    float4 BaseColorUVScaleBias;\n"
"    float4 PhysicalDescriptorUVScaleBias;\n"
"    float4 NormalMapUVScaleBias;\n"
"    float4 OcclusionUVScaleBias;\n"
"    float4 EmissiveUVScaleBias;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(GLTFMaterialShaderInfo);\n"
"#endif\n"
"\n"
"#endif // _GLTF_PBR_STRUCTURES_FXH_\n"
