"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"#include \"GLTF_PBR_PrecomputeCommon.fxh\"\n"
"\n"
"#define NUM_SAMPLES 256u\n"
"\n"
"void PrecomputeBRDF_PS(FullScreenTriangleVSOutput VSOut,\n"
"                       out float2 f2BRDF : SV_Target)\n"
"{\n"
"    f2BRDF = BRDF(VSOut.f2NormalizedXY.x, VSOut.f2NormalizedXY.y, NUM_SAMPLES);\n"
"}\n"
