"#include \"BasicStructures.fxh\"\n"
"#include \"PBR_Structures.fxh\"\n"
"#include \"RenderPBR_Structures.fxh\"\n"
"\n"
"#include \"VSOutputStruct.generated\"\n"
"\n"
"cbuffer cbFrameAttribs\n"
"{\n"
"    PBRFrameAttribs g_Frame;\n"
"}\n"
"\n"
"cbuffer cbPrimitiveAttribs\n"
"{\n"
"    PBRPrimitiveAttribs g_Primitive;\n"
"}\n"
"\n"
"#include \"PSOutputStruct.generated\"\n"
"// struct PSOutput\n"
"// {\n"
"//     float4 Color : SV_Target0;\n"
"// };\n"
"\n"
"PSOutput main(in VSOutput VSOut,\n"
"              in bool     IsFrontFace : SV_IsFrontFace)\n"
"{\n"
"#include \"PSMainFooter.generated\"\n"
"    //PSOutput PSOut;\n"
"    //PSOut.Color = g_Frame.Renderer.UnshadedColor + g_Frame.Renderer.HighlightColor;\n"
"    //return PSOut;\n"
"}\n"
