"#include \"BasicStructures.fxh\"\n"
"#include \"GLTF_PBR_VertexProcessing.fxh\"\n"
"\n"
"struct GLTF_VS_Input\n"
"{\n"
"    float3 Pos     : ATTRIB0;\n"
"    float3 Normal  : ATTRIB1;\n"
"    float2 UV0     : ATTRIB2;\n"
"    float2 UV1     : ATTRIB3;\n"
"    float4 Joint0  : ATTRIB4;\n"
"    float4 Weight0 : ATTRIB5;\n"
"};\n"
"\n"
"cbuffer cbCameraAttribs\n"
"{\n"
"    CameraAttribs g_CameraAttribs;\n"
"}\n"
"\n"
"cbuffer cbTransforms\n"
"{\n"
"    GLTFNodeShaderTransforms g_Transforms;\n"
"}\n"
"    \n"
"void main(in  GLTF_VS_Input  VSIn,\n"
"          out float4 ClipPos  : SV_Position,\n"
"          out float3 WorldPos : WORLD_POS,\n"
"          out float3 Normal   : NORMAL,\n"
"          out float2 UV0      : UV0,\n"
"          out float2 UV1      : UV1) \n"
"{\n"
"    GLTF_Vertex Vert;\n"
"    Vert.Pos     = VSIn.Pos;\n"
"    Vert.Normal  = VSIn.Normal;\n"
"    Vert.Joint0  = VSIn.Joint0;\n"
"    Vert.Weight0 = VSIn.Weight0;\n"
"\n"
"    GLTF_TransformedVertex TransformedVert = GLTF_TransformVertex(Vert, g_Transforms);\n"
"\n"
"    ClipPos  = mul(float4(TransformedVert.WorldPos, 1.0), g_CameraAttribs.mViewProj);\n"
"    WorldPos = TransformedVert.WorldPos;\n"
"    Normal   = TransformedVert.Normal;\n"
"    UV0      = VSIn.UV0;\n"
"    UV1      = VSIn.UV1;\n"
"}\n"
