"#ifndef _RENDER_PBR_STRUCTURES_FXH_\n"
"#define _RENDER_PBR_STRUCTURES_FXH_\n"
"\n"
"// #include \"BasicStructures.fxh\"\n"
"// #include \"PBR_Structures.fxh\"\n"
"\n"
"\n"
"struct PBRFrameAttribs\n"
"{\n"
"    CameraAttribs               Camera;\n"
"    PBRRendererShaderParameters Renderer;\n"
"    PBRLightAttribs             Light;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRFrameAttribs);\n"
"#endif\n"
"\n"
"\n"
"struct PBRPrimitiveAttribs\n"
"{\n"
"    GLTFNodeShaderTransforms Transforms;\n"
"    PBRMaterialShaderInfo    Material;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRPrimitiveAttribs);\n"
"#endif\n"
"\n"
"\n"
"#endif // _RENDER_PBR_STRUCTURES_FXH_\n"
