"#include \"BasicStructures.fxh\"\n"
"#include \"PBR_Structures.fxh\"\n"
"#include \"RenderPBR_Structures.fxh\"\n"
"\n"
"#include \"VSOutputStruct.generated\"\n"
"\n"
"cbuffer cbFrameAttribs\n"
"{\n"
"    PBRFrameAttribs g_Frame;\n"
"}\n"
"\n"
"cbuffer cbPrimitiveAttribs\n"
"{\n"
"    PBRPrimitiveAttribs g_Primitive;\n"
"}\n"
"\n"
"#include \"PSMainGenerated.generated\"\n"
"//void main(in  VSOutput VSOut,\n"
"//          out float4   OutColor : SV_Target)\n"
"//{\n"
"//    OutColor = g_Frame.Renderer.WireframeColor;\n"
"//}\n"
