"#ifndef _RENDER_PBR_STRUCTURES_FXH_\n"
"#define _RENDER_PBR_STRUCTURES_FXH_\n"
"\n"
"// #include \"BasicStructures.fxh\"\n"
"// #include \"PBR_Structures.fxh\"\n"
"\n"
"#ifndef COMPUTE_MOTION_VECTORS\n"
"#   define COMPUTE_MOTION_VECTORS 0\n"
"#endif\n"
"\n"
"struct PBRFrameAttribs\n"
"{\n"
"    CameraAttribs               Camera;\n"
"    CameraAttribs               PrevCamera; // Previous frame camera used to compute motion vectors\n"
"    PBRRendererShaderParameters Renderer;\n"
"    PBRLightAttribs             Light;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRFrameAttribs);\n"
"#endif\n"
"\n"
"\n"
"struct PBRPrimitiveAttribs\n"
"{\n"
"    GLTFNodeShaderTransforms Transforms;\n"
"#if COMPUTE_MOTION_VECTORS\n"
"    float4x4                 PrevNodeMatrix;\n"
"#endif\n"
"    PBRMaterialShaderInfo    Material;\n"
"\n"
"    float4 CustomData;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRPrimitiveAttribs);\n"
"#endif\n"
"\n"
"\n"
"#endif // _RENDER_PBR_STRUCTURES_FXH_\n"
