"#include \"RenderPBRCommon.fxh\"\n"
"#include \"PBR_Structures.fxh\"\n"
"\n"
"cbuffer cbPBRAttribs\n"
"{\n"
"    PBRShaderAttribs g_PBRAttribs;\n"
"}\n"
"\n"
"void main(in PbrVsOutput VSOut,\n"
"          out float4 OutColor : SV_Target)\n"
"{\n"
"    OutColor = g_PBRAttribs.Renderer.WireframeColor;\n"
"}\n"
