"#include \"RenderPBRCommon.fxh\"\n"
"#include \"PBR_Structures.fxh\"\n"
"\n"
"cbuffer cbPBRAttribs\n"
"{\n"
"    PBRShaderAttribs g_PBRAttribs;\n"
"}\n"
"\n"
"void main(in PbrVsOutput VSOut,\n"
"          out uint4 OutMeshId : SV_Target)\n"
"{\n"
"    OutMeshId.r = (g_PBRAttribs.Renderer.MeshId >> 0u) & 0xFFu;\n"
"    OutMeshId.g = (g_PBRAttribs.Renderer.MeshId >> 8u) & 0xFFu;\n"
"    OutMeshId.b = (g_PBRAttribs.Renderer.MeshId >> 16u) & 0xFFu;\n"
"    OutMeshId.a = (g_PBRAttribs.Renderer.MeshId >> 24u) & 0xFFu;\n"
"    //OutMeshId.r = float((g_PBRAttribs.Renderer.MeshId >>  0u) & 0xFFu) / 255.0;\n"
"    //OutMeshId.g = float((g_PBRAttribs.Renderer.MeshId >>  8u) & 0xFFu) / 255.0;\n"
"    //OutMeshId.b = float((g_PBRAttribs.Renderer.MeshId >> 16u) & 0xFFu) / 255.0;\n"
"    //OutMeshId.a = float((g_PBRAttribs.Renderer.MeshId >> 24u) & 0xFFu) / 255.0;\n"
"}\n"
