"#ifndef _SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
"#define _SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
"\n"
"#ifdef __cplusplus\n"
"\n"
"#   ifndef BOOL\n"
"#      define BOOL int32_t // Do not use bool, because sizeof(bool)==1 !\n"
"#   endif\n"
"\n"
"#   ifndef TRUE\n"
"#      define TRUE 1\n"
"#   endif\n"
"\n"
"#   ifndef FALSE\n"
"#      define FALSE 0\n"
"#   endif\n"
"\n"
"#   ifndef CHECK_STRUCT_ALIGNMENT\n"
"        // Note that defining empty macros causes GL shader compilation error on Mac, because\n"
"        // it does not allow standalone semicolons outside of main.\n"
"        // On the other hand, adding semicolon at the end of the macro definition causes gcc error.\n"
"#       define CHECK_STRUCT_ALIGNMENT(s) static_assert( sizeof(s) % 16 == 0, \"sizeof(\" #s \") is not multiple of 16\" )\n"
"#   endif\n"
"\n"
"#   ifndef DEFAULT_VALUE\n"
"#       define DEFAULT_VALUE(x) =x\n"
"#   endif\n"
"\n"
"#else\n"
"\n"
"#   ifndef BOOL\n"
"#       define BOOL bool\n"
"#   endif\n"
"\n"
"#   ifndef DEFAULT_VALUE\n"
"#       define DEFAULT_VALUE(x)\n"
"#   endif\n"
"\n"
"#endif\n"
"\n"
"#define SSR_DEPTH_HIERARCHY_MAX_MIP 6\n"
"\n"
"#define SSR_SPATIAL_RECONSTRUCTION_SAMPLES 16\n"
"\n"
"#define SSR_SPATIAL_RECONSTRUCTION_ROUGHNESS_FACTOR 5\n"
"\n"
"#define SSR_DISOCCLUSION_DEPTH_WEIGHT 1.0\n"
"\n"
"#define SSR_DISOCCLUSION_THRESHOLD 0.9\n"
"\n"
"#define SSR_TEMPORAL_STANDARD_DEVIATION_SCALE 2.0\n"
"\n"
"#define SSR_BILATERAL_SIGMA_NORMAL 128.0\n"
"\n"
"#define SSR_BILATERAL_SIGMA_DEPTH 1.0\n"
"\n"
"#define SSR_BILATERAL_VARIANCE_EXIT_THRESHOLD 0.00005\n"
"\n"
"#define SSS_BILATERAL_VARIANCE_ESTIMATE_THRESHOLD 0.001\n"
"\n"
"#define SSR_BILATERAL_ROUGHNESS_FACTOR 8\n"
"\n"
"struct ScreenSpaceReflectionAttribs\n"
"{\n"
"    float4x4 ProjMatrix;\n"
"    float4x4 ViewMatrix;\n"
"    float4x4 ViewProjMatrix;\n"
"    float4x4 PrevViewProjMatrix;\n"
"\n"
"    float4x4 InvProjMatrix;\n"
"    float4x4 InvViewMatrix;\n"
"    float4x4 InvViewProjMatrix;\n"
"    float4x4 InvPrevViewProjMatrix;\n"
"\n"
"    float4 CameraPosition;\n"
"    float2 InverseRenderSize;\n"
"    int2   RenderSize;\n"
"\n"
"    float IBLFactor                            DEFAULT_VALUE(1.0f);\n"
"    float DepthBufferThickness                 DEFAULT_VALUE(0.015f);\n"
"    float RoughnessThreshold                   DEFAULT_VALUE(0.2f);\n"
"    uint  MostDetailedMip                      DEFAULT_VALUE(0);\n"
"\n"
"    BOOL IsRoughnessPerceptual                 DEFAULT_VALUE(TRUE);\n"
"    uint RoughnessChannel                      DEFAULT_VALUE(0);\n"
"    uint FrameIndex                            DEFAULT_VALUE(0);\n"
"    uint MaxTraversalIntersections             DEFAULT_VALUE(128);\n"
"\n"
"    float GGXImportanceSampleBias              DEFAULT_VALUE(0.3f);\n"
"    float SpatialReconstructionRadius          DEFAULT_VALUE(4.0f);\n"
"    float TemporalRadianceStabilityFactor      DEFAULT_VALUE(1.0f);\n"
"    float TemporalVarianceStabilityFactor      DEFAULT_VALUE(0.9f);\n"
"\n"
"    float BilateralCleanupSpatialSigmaFactor   DEFAULT_VALUE(0.9f);\n"
"    float Padding0;\n"
"    float Padding1;\n"
"    float Padding2;\n"
"};\n"
"\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(ScreenSpaceReflectionAttribs);\n"
"#endif\n"
"\n"
"#endif //_SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
