"#include \"AtmosphereShadersCommon.fxh\"\n"
"\n"
"ScreenSizeQuadVSOutput ScreenSizeQuadVS(in uint VertexId : SV_VertexID,\n"
"                                        in uint InstID : SV_InstanceID,\n"
"                                        // IMPORTANT: PS input arguments must go in the same order as VS outputs.\n"
"                                        // Moreover, even if the shader is not using the argument,\n"
"                                        // it still must be declared.\n"
"                                        out float4 f4Pos : SV_Position)\n"
"{\n"
"    ScreenSizeQuadVSOutput VSOut;\n"
"    float4 Bounds = float4(-1.0, -1.0, 1.0, 1.0);\n"
"    \n"
"    float2 PosXY[4];\n"
"    PosXY[0] = Bounds.xy;\n"
"    PosXY[1] = Bounds.xw;\n"
"    PosXY[2] = Bounds.zy;\n"
"    PosXY[3] = Bounds.zw;\n"
"\n"
"    float2 f2XY = PosXY[VertexId];\n"
"    VSOut.m_f2PosPS = f2XY;\n"
"    VSOut.m_fInstID = float( InstID );\n"
"    \n"
"    // Write 0 to the depth buffer\n"
"    // NDC_MIN_Z ==  0 in DX\n"
"    // NDC_MIN_Z == -1 in GL\n"
"    float z = NDC_MIN_Z;\n"
"    f4Pos = float4(f2XY, z, 1.0);\n"
"\n"
"    return VSOut;\n"
"}\n"
