"\n"
"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"\n"
"struct ConversionAttribs\n"
"{\n"
"    int iCascade;\n"
"};\n"
"\n"
"cbuffer cbConversionAttribs\n"
"{\n"
"    ConversionAttribs g_Attribs;\n"
"}\n"
"\n"
"Texture2DArray g_tex2DShadowMap;\n"
"\n"
"void VSMHorzPS(FullScreenTriangleVSOutput VSOut,\n"
"               out float4 f2Moments : SV_Target)\n"
"{\n"
"    float fDepth = g_tex2DShadowMap.Load( int4(VSOut.f4PixelPos.xy, g_Attribs.iCascade, 0) ).r;\n"
"    f2Moments = float4(fDepth, fDepth*fDepth, 0.0, 0.0);\n"
"}\n"
"\n"
"void VSMVertPS(FullScreenTriangleVSOutput VSOut,\n"
"               out float4 f2Moments : SV_Target)\n"
"{\n"
"    float2 f2MomentsHorx = g_tex2DShadowMap.Load( int4(VSOut.f4PixelPos.xy, g_Attribs.iCascade, 0) ).rg;\n"
"    f2Moments = float4(f2MomentsHorx, 0.0, 0.0);\n"
"}\n"
"\n"
