"\n"
"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"\n"
"struct ConversionAttribs\n"
"{\n"
"    int iCascade;\n"
"    int iFilterRadius;\n"
"};\n"
"\n"
"cbuffer cbConversionAttribs\n"
"{\n"
"    ConversionAttribs g_Attribs;\n"
"}\n"
"\n"
"Texture2DArray g_tex2DShadowMap;\n"
"\n"
"float4 VSMHorzPS(FullScreenTriangleVSOutput VSOut) : SV_Target\n"
"{\n"
"    float2 f2Moments = float2(0.0, 0.0);\n"
"    for (int i = -g_Attribs.iFilterRadius; i <= +g_Attribs.iFilterRadius; ++i)\n"
"    {\n"
"        float fDepth = g_tex2DShadowMap.Load( int4( int(VSOut.f4PixelPos.x) + i, int(VSOut.f4PixelPos.y), g_Attribs.iCascade, 0) ).r;\n"
"        f2Moments += float2(fDepth, fDepth*fDepth);\n"
"    }\n"
"    return float4(f2Moments / float(g_Attribs.iFilterRadius*2 + 1), 0.0, 0.0);\n"
"}\n"
"\n"
"float4 VSMVertPS(FullScreenTriangleVSOutput VSOut) : SV_Target\n"
"{\n"
"    float2 f2Moments = float2(0.0, 0.0);\n"
"    for (int i = -g_Attribs.iFilterRadius; i <= +g_Attribs.iFilterRadius; ++i)\n"
"    {\n"
"        f2Moments += g_tex2DShadowMap.Load( int4( int(VSOut.f4PixelPos.x), int(VSOut.f4PixelPos.y) + i, 0, 0) ).rg;\n"
"    }\n"
"    return float4(f2Moments / float(g_Attribs.iFilterRadius*2 + 1), 0.0, 0.0);\n"
"}\n"
