"struct VectorFieldRenderAttribs\n"
"{\n"
"    float4 ScaleAndBias;\n"
"\n"
"    float fGridWidth;\n"
"    float fGridHeight;\n"
"    uint  uGridWidth;\n"
"    uint  uGridHeight;\n"
"\n"
"    float4 Colors[2];\n"
"};\n"
"\n"
"cbuffer cbAttribs\n"
"{\n"
"    VectorFieldRenderAttribs g_Attribs;\n"
"}\n"
"\n"
"Texture2D    g_tex2DVectorField;\n"
"SamplerState g_tex2DVectorField_sampler;\n"
"\n"
"void main(in  uint   VertexId : SV_VertexID,\n"
"          out float4 Pos      : SV_Position,\n"
"          out float4 Color    : COLOR)\n"
"{\n"
"    uint Col = (VertexId / 2u) % g_Attribs.uGridWidth;\n"
"    uint Row = (VertexId / 2u) / g_Attribs.uGridWidth;\n"
"\n"
"    float2 UV = float2(\n"
"        (float(Col) + 0.5) / g_Attribs.fGridWidth,\n"
"        (float(Row) + 0.5) / g_Attribs.fGridHeight);\n"
"\n"
"    float2 MotionVec = g_tex2DVectorField.SampleLevel(g_tex2DVectorField_sampler, UV, 0.0).xy;\n"
"    MotionVec = (MotionVec + g_Attribs.ScaleAndBias.zw) * g_Attribs.ScaleAndBias.xy;\n"
"\n"
"    float2 PosXY = TexUVToNormalizedDeviceXY(UV);\n"
"    if ((VertexId & 0x01u) != 0u)\n"
"    {\n"
"        PosXY += MotionVec;\n"
"    }\n"
"\n"
"    Pos   = float4(PosXY, 0.0, 1.0);\n"
"    Color = g_Attribs.Colors[VertexId & 0x01u];\n"
"}\n"
