sudo: required

language: cpp

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - git clone https://github.com/DiligentGraphics/DiligentCore.git ../DiligentCore --recursive
  - git clone https://github.com/DiligentGraphics/DiligentTools.git ../DiligentTools --recursive
  - . ../DiligentCore/BuildTools/Scripts/travis/before_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

matrix:
  include:
  - os: linux
    compiler: gcc
    env: CONFIG=Release
  - os: osx
    compiler: clang
    env:
      - CONFIG=Release
      - IOS=false
  - os: linux
    compiler: gcc
    env: CONFIG=Debug
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=true

script:

  # Run cmake
  - cd ..
  - |
    echo "cmake_minimum_required(VERSION 3.6)" > CMakeLists.txt
    echo "Project(DiligentFX_Test)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentCore)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentTools)" >> CMakeLists.txt
    echo "add_subdirectory(DiligentFX)" >> CMakeLists.txt
  - mkdir build
  - cd build
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_INSTALL_PREFIX=install
      cmake --build . --target install
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      if [ "$IOS" = "true" ]; then 
        cmake .. -DCMAKE_TOOLCHAIN_FILE=../DiligentCore/ios.toolchain.cmake -DIOS_PLATFORM=OS64 -DIOS_ARCH=arm64 -DVULKAN_SDK="$VULKAN_SDK" -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
      else
        cmake .. -DCMAKE_INSTALL_PREFIX=install -G "Xcode"
      fi
      cmake --build . --target install --config ${CONFIG} | xcpretty
    fi

after_success:

  - cd ../build/install
  - export ZIP_NAME=DiligentFX-${TRAVIS_OS_NAME}-${GLSLANG_BUILD_TYPE}.zip;
  - zip -r ${ZIP_NAME} .
