"#ifndef _HN_AXES_STRUCTURES_FXH_\n"
"#define _HN_AXES_STRUCTURES_FXH_\n"
"\n"
"struct AxesConstants\n"
"{\n"
"    float4x4 Transform;\n"
"    float4   AxesColors[6]; // -X, +X, -Y, +Y, -Z, +Z\n"
"};\n"
"\n"
"#endif // _HN_AXES_STRUCTURES_FXH_\n"
