"#ifndef _HN_CLOSEST_SELECTED_LOCATION_FXH_\n"
"#define _HN_CLOSEST_SELECTED_LOCATION_FXH_\n"
"\n"
"struct ClosestSelectedLocationConstants\n"
"{\n"
"    float ClearDepth;\n"
"    float SampleRange;\n"
"    float Padding1;\n"
"    float Padding2;\n"
"};\n"
"\n"
"#ifndef __cplusplus\n"
"float2 EncodeClosestSelectedLocation(float2 Location, bool IsValid)\n"
"{\n"
"    if (IsValid)\n"
"    {\n"
"        Location.y = Location.y * 0.5 + 0.5;\n"
"        return Location;\n"
"    }\n"
"    else\n"
"    {\n"
"        return float2(0.0, 0.0);\n"
"    }\n"
"}\n"
"\n"
"void DecodeClosestSelectedLocation(in  float2 EncodedLocation,\n"
"                                   out float2 Location,\n"
"                                   out bool   IsValid)\n"
"{\n"
"    if (EncodedLocation.y <= 0.25)\n"
"    {\n"
"        IsValid  = false;\n"
"        Location = float2(0.0, 0.0);\n"
"    }\n"
"    else\n"
"    {\n"
"        Location   = EncodedLocation;\n"
"        Location.y = Location.y * 2.0 - 1.0;\n"
"        IsValid    = true;\n"
"    }\n"
"}\n"
"#endif\n"
"\n"
"#endif // _HN_CLOSEST_SELECTED_LOCATION_FXH_\n"
