"#include \"HnClosestSelectedLocation.fxh\"\n"
"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"\n"
"cbuffer cbConstants\n"
"{\n"
"    ClosestSelectedLocationConstants g_Constants;\n"
"}\n"
"\n"
"Texture2D g_SelectionDepth;\n"
"\n"
"void main(in  FullScreenTriangleVSOutput VSOut,\n"
"          out float2                     Location : SV_Target0)\n"
"{\n"
"    bool IsSelected = g_SelectionDepth.Load(int3(VSOut.f4PixelPos.xy, 0)).r != g_Constants.ClearDepth;\n"
"    float Width;\n"
"    float Height;\n"
"    g_SelectionDepth.GetDimensions(Width, Height);\n"
"    Location = EncodeClosestSelectedLocation(VSOut.f4PixelPos.xy / float2(Width, Height), IsSelected);\n"
"}\n"
