"#include \"HnClosestSelectedLocation.fxh\"\n"
"\n"
"struct PSInput\n"
"{\n"
"    float4 Pos : SV_POSITION;\n"
"};\n"
"\n"
"cbuffer cbConstants\n"
"{\n"
"    ClosestSelectedLocationConstants g_Constants;\n"
"}\n"
"\n"
"Texture2D g_SelectionDepth;\n"
"\n"
"void main(in  PSInput PSIn,\n"
"          out float2  Location : SV_Target0)\n"
"{\n"
"    bool IsSelected = g_SelectionDepth.Load(int3(PSIn.Pos.xy, 0)).r != g_Constants.ClearDepth;\n"
"    float Width;\n"
"    float Height;\n"
"    g_SelectionDepth.GetDimensions(Width, Height);\n"
"    Location = EncodeClosestSelectedLocation(PSIn.Pos.xy / float2(Width, Height), IsSelected);\n"
"}\n"
