"#ifndef _HN_POST_PROCESS_STRUCTURES_FXH_\n"
"#define _HN_POST_PROCESS_STRUCTURES_FXH_\n"
"\n"
"struct PostProcessAttribs\n"
"{\n"
"    float4 SelectionOutlineColor;\n"
"\n"
"    float NonselectionDesaturationFactor;\n"
"    float Padding0;\n"
"    float Padding1;\n"
"    float Padding2;\n"
"};\n"
"\n"
"#endif // _HN_POST_PROCESS_STRUCTURES_FXH_\n"
