"struct PSInput\n"
"{\n"
"    float4 Pos : SV_POSITION;\n"
"};\n"
"void main(in  uint    VertID : SV_VertexID,\n"
"          out PSInput PSIn)\n"
"{\n"
"    float2 ClipXY[3];\n"
"    ClipXY[0] = float2(-1.0, -1.0);\n"
"    ClipXY[1] = float2(-1.0,  3.0);\n"
"    ClipXY[2] = float2( 3.0, -1.0);\n"
"\n"
"    PSIn.Pos = float4(ClipXY[VertID], 0.0, 1.0);\n"
"}\n"
