name: Emscripten build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:         ["windows-latest", "ubuntu-24.04", "macos-14"]
        build_type: ["Debug", "Release"]

        exclude:
          # Exclude MacOS-Release
          - os:         "macos-14"
            build_type: "Release"

        include:
          - os:         "windows-latest"
            host_name:  "Win10"
            cmake_args: "-DDILIGENT_NO_WEBGPU=ON"

          - os:         "ubuntu-24.04"
            host_name:  "Linux"
            cmake_args: "-DDILIGENT_NO_WEBGPU=ON"

          - os:         "macos-14"
            host_name:  "MacOS"
            cmake_args: "-DDILIGENT_NO_WEBGPU=ON"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.host_name }} -> Emscripten, ${{ matrix.build_type }}

    steps:
    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v7

    - name: Set up build environment
      if:   success()
      uses: DiligentGraphics/github-action/setup-build-env@v7
      with:
        platform: Web

    - name: Configure CMake
      if:   success()
      uses: DiligentGraphics/github-action/configure-cmake@v7
      with:
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if:   success()
      uses: DiligentGraphics/github-action/build@v7
