name: Win32/UWP build

on: [push, pull_request]

jobs:
  precheks:
    name:    Win10 -> Pre-checks
    runs-on: windows-latest

    steps:
    - name: Clone DiligentCore
      uses: actions/checkout@v3
      with:
        repository: DiligentGraphics/DiligentCore
        path:       DiligentCore

    - name: Clone DiligentFX
      uses: actions/checkout@v3
      with:
        path: DiligentFX

    - name: Format validation
      shell: cmd
      working-directory: ${{github.workspace}}/DiligentFX/BuildTools/FormatValidation
      run: validate_format_win.bat


  build:
    needs:   precheks
    runs-on: windows-2022

    strategy:
      matrix:
        name:            ["Win10"]
        toolset:         ["Win32", "x64"]
        build_type:      ["Debug", "Release"]
        cmake_generator: ["Visual Studio 17 2022"]
        cmake_args:      ["-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON -DDILIGENT_BUILD_FX_INCLUDE_TEST=ON"]
        platform:        ["Win32"]

        include:
          - name:            "Win10-Dev"
            platform:        "Win32"
            toolset:         "x64"
            build_type:      "RelWithDebInfo"
            cmake_generator: "Visual Studio 17 2022"
            cmake_args:      "-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON -DDILIGENT_DEVELOPMENT=ON"

          - name:            "Win10-Ninja"
            platform:        "Win32"
            toolset:         "x64"
            build_type:      "Debug"
            cmake_generator: "Ninja"
            cmake_args:      "-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON"

          - name:            "MinGW"
            platform:        "Win32"
            toolset:         "x64"
            build_type:      "Release"
            cmake_generator: "MinGW Makefiles"
            cmake_args:      "-DDILIGENT_NO_GLSLANG=ON -DDILIGENT_NO_HLSL=ON"

          - name:            "UWP"
            platform:        "UWP"
            toolset:         "x64"
            build_type:      "Debug"
            cmake_generator: "Visual Studio 17 2022"
            cmake_args:      "-DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0"

          - name:            "UWP"
            platform:        "UWP"
            toolset:         "x64"
            build_type:      "Release"
            cmake_generator: "Visual Studio 17 2022"
            cmake_args:      "-DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0"

    name: Win10 -> ${{ matrix.name }}-${{ matrix.toolset }}, ${{ matrix.build_type }}

    steps:
    - name: Checkout
      uses: DiligentGraphics/github-action/checkout@v1

    - name: Set up build environment
      if: success()
      uses: DiligentGraphics/github-action/setup-build-env@v1
      with:
        platform:        ${{ matrix.platform }}
        cmake-generator: ${{ matrix.cmake_generator }}
        ninja-vs-arch:   ${{ matrix.toolset }}

    - name: Configure CMake
      if: success()
      uses: DiligentGraphics/github-action/configure-cmake@v1
      with:
        generator:  ${{ matrix.cmake_generator }}
        vs-arch:    ${{ matrix.toolset }}
        build-type: ${{ matrix.build_type }}
        cmake-args: ${{ matrix.cmake_args }}

    - name: Build
      if: success()
      uses: DiligentGraphics/github-action/build@v1
