name: UWP

on: [push, pull_request]

jobs:
  build-uwp:
    strategy:
      matrix:
        toolset: [x64]
        config: [Debug, Release]

    runs-on: windows-latest
    name: Win10 -> UWP-${{ matrix.toolset }}, ${{ matrix.config }} 

    steps:
    - name: Clone DiligentFX
      uses: actions/checkout@v2
      with:
        path:       DiligentFX
        submodules: recursive

    - name: Clone DiligentTools
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentTools'
        path:       DiligentTools
        submodules: recursive

    - name: Clone DiligentCore
      uses: actions/checkout@v2
      with:
        repository: 'DiligentGraphics/DiligentCore'
        path:       DiligentCore
        submodules: recursive

    - name: Configure CMake
      if: success()
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/DiligentFX/BuildTools/Scripts/github_actions
        ./create_cmake.sh "$GITHUB_WORKSPACE"
        cd $GITHUB_WORKSPACE/DiligentCore/BuildTools/Scripts/github_actions
        ./configure_cmake.sh "uwp" "${{runner.workspace}}" ${{ matrix.toolset }} ${{ matrix.config }}

    - name: Build
      if: success()
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.config }} -j2
